const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("dailyOps", {
  status: () => ipcRenderer.invoke("api:status"),
  outputs: (limit) => ipcRenderer.invoke("api:outputs", limit),
  reports: () => ipcRenderer.invoke("api:reports"),
  sourceGroups: () => ipcRenderer.invoke("api:source-groups"),
  selectFiles: (group) => ipcRenderer.invoke("api:select-files", group),
  uploadSource: (group, filePaths, payload) => ipcRenderer.invoke("api:upload-source", group, filePaths, payload || {}),
  finishUpload: (category, payload) => ipcRenderer.invoke("api:finish-upload", category, payload || {}),
  clearUpload: (category, payload) => ipcRenderer.invoke("api:clear-upload", category, payload || {}),
  generateWeekly: (payload) => ipcRenderer.invoke("api:generate-weekly", payload || {}),
  generateReport: (reportId, version, payload) => ipcRenderer.invoke("api:generate-report", reportId, version, payload || {}),
  openOutput: (name) => ipcRenderer.invoke("api:open-output", name),
  revealOutput: (name) => ipcRenderer.invoke("api:reveal-output", name),
  loadRules: () => ipcRenderer.invoke("api:load-rules"),
  saveRules: (payload) => ipcRenderer.invoke("api:save-rules", payload || {}),
  search: (query, limit, payload) => ipcRenderer.invoke("api:search", query, limit, payload || {}),
  tasks: (filters) => ipcRenderer.invoke("api:tasks", filters || {}),
  submitTask: (payload) => ipcRenderer.invoke("api:submit-task", payload || {}),
  assignTask: (payload) => ipcRenderer.invoke("api:assign-task", payload || {}),
  reviewTask: (payload) => ipcRenderer.invoke("api:review-task", payload || {}),
  batchReviewTasks: (payload) => ipcRenderer.invoke("api:batch-review-tasks", payload || {}),
  doneTask: (payload) => ipcRenderer.invoke("api:done-task", payload || {}),
  exportTasks: (payload) => ipcRenderer.invoke("api:export-tasks", payload || {}),
  storeOwners: (payload) => ipcRenderer.invoke("api:store-owners", payload || {}),
  saveStoreOwners: (payload) => ipcRenderer.invoke("api:save-store-owners", payload || {}),
  createBackup: (payload) => ipcRenderer.invoke("api:create-backup", payload || {}),
  restoreBackup: (payload) => ipcRenderer.invoke("api:restore-backup", payload || {}),
});
